import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Icon from '../public/ono.svg'
import Image from 'next/image'
import Sidebar from './sidebar'
import {
    
} from './layout.module.css'

export default function Layout({children}) {
    return (
        <div className={styles.container}>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={navcontainer}>
                    <Image src={Icon} alt="ONO ICON"/>
                    <nav>
                        <Sidebar />
                    </nav>
                </div>
            </main>
            <footer className={styles.footer}>
            </footer>
        </div>
    )
}